### PR TITLE
Emulator: Upgrade from gbajs to gbajs2.

### PR DESCRIPTION
**Pull request by lofoz**

### CODE REVIEW

**Comment by lofoz** [comment]
gbajs2: https://github.com/andychase/gbajs2

**Comment by macabeus** [comment]
Hello. I'm sorry for the delay in reviewing this PR. I'll try to do it as soon as possible.

**Comment by macabeus** [comment]
Hey, I'm on business travel, and I'll be able to check this PR only on the upcoming weekend.
I don't want to delay it for so long.

If you can test your changes on [`klo-gba.js`](https://github.com/macabeus/klo-gba.js), it would be great.

**Comment by lofoz** [comment]
No problem, I will test the changes on klo-gba.js in these two days.
Thanks for your help!

**Comment by macabeus** [comment]
Hey, I finally tested this PR, and it isn't working.
When I try to run `npm run start` or `npm run build`, it failed because of missing a babel configuration.
And even after fixing it with the following patch:
```diff
index f108ead..75e604b 100644
--- a/.babelrc
+++ b/.babelrc
@@ -1,6 +1,7 @@
 {
   "presets": ["@babel/preset-env", "@babel/react"],
   "plugins": [
-    ["@babel/transform-runtime"]
+    ["@babel/transform-runtime"],
+    ["@babel/plugin-proposal-class-properties"]
   ]
 }
```
```diff
index 01871cb..13e2680 100644
--- a/package.json
+++ b/package.json
@@ -27,6 +27,7 @@
   },
   "devDependencies": {
     "@babel/core": "7.7.2",
+    "@babel/plugin-proposal-class-properties": "^7.18.6",
     "@babel/preset-env": "7.7.1",
     "@babel/preset-react": "7.7.0",
     "arraybuffer-loader": "1.0.8",
```

I have the following error on the sample project:
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'setCanvas')
```

**Comment by macabeus** [comment]
Staled

**Pull request closed without merging**
